# Generated by Django 3.0.5 on 2020-10-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('created_dttm', models.DateField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('trans_type', models.CharField(max_length=200)),
                ('created_dttm', models.DateField(verbose_name='date created')),
                ('bankroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankrolls.Bankroll')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dttm', models.DateTimeField()),
                ('end_dttm', models.DateTimeField()),
                ('buy_in', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('max_table_size', models.IntegerField(default=0)),
                ('session_type', models.CharField(max_length=32)),
                ('bankroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankrolls.Bankroll')),
            ],
        ),
    ]
