# Generated by Django 3.0.5 on 2020-09-09 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('created_dttm', models.DateField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('trans_type', models.CharField(max_length=200)),
                ('created_dttm', models.DateField(verbose_name='date created')),
                ('bankroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankrolls.Bankroll')),
            ],
        ),
    ]
